spring:

  application:
    name: purchase

  datasource:
    url: jdbc:h2:mem:purchase
    username: sa
    password: changeit

    ### Spring devtools add-properties and restart should not be enabled in production.
    #devtools:
    #add-properties: false
    #restart.enabled: false

  jpa:
    database: h2
