app:
  purchase:
    treasury-fiscalData:
      base-url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/
      rates_of_exchange-endpoint: v1/accounting/od/rates_of_exchange
      cache-enabled: true

spring:
  application:
    name: purchase

  ### For H2 support, uncomment this h2 datasource and comment out the postgresql datasource.
  datasource:
    url: jdbc:h2:mem:purchase
    username: sa
    password: changeit

  ### For PostgreSQL support, uncomment this postgresql datasource and comment out the h2 datasource.
  #datasource:
    #url: jdbc:postgresql://localhost:5433/purchase
    #username: dconneely
    #password: dconneely

  ### spring.devtools.add-properties and spring.devtools.restart.enabled should be "false" in production.
    #devtools:
      #add-properties: false
      #restart.enabled: false

  ### spring.jpa.database should be "H2" for the embedded database, or "POSTGRESQL" for production.
  jpa:
    database: H2

  ### The XML format is more compact and easier to read than the YAML format.
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

springdoc:
  ### springdoc.api-docs.enabled and springdoc.swagger-ui.enabled should be "false" in production.
  api-docs.enabled: true
  paths-to-exclude: /*/, /*/*/
  swagger-ui.enabled: true
